name: Jira

on:
  workflow_call:
    inputs:
      project:
        description: The key of the Jira project to create the issue in
        required: true
        type: string
      github_team:
        description: The name of the GitHub Org team to assign the issue to
        required: true
        type: string
      dependabot_exclude_team_members:
        description: Comma-separated list of team members to exclude from being assigned as reviewer when Dependabot opens a PR
        required: false
        type: string
      issue_type:
        description: The type of issue to create
        required: false
        default: Task
        type: string
      labels:
        description: Comma-separated list of labels to apply to the issue
        required: false
        default: security, dependabot
        type: string
    secrets:
      JIRA_BASE_URL:
        required: true
      JIRA_USER_EMAIL:
        required: true
      JIRA_API_TOKEN:
        required: true
      ORG_TEAM_MEMBERS:
        required: true

jobs:
  Create: # Create a new Jira issue when a PR is opened by dependabot, or when a PR is labeled with 'process-existing-pr'
    runs-on: ubuntu-latest
    steps:
      - name: Skip remaining steps # Run this rather than just skipping the whole job, so that we see a green tick in the PR checks
        if: >- # Specificity is important here to avoid triggering this action multiple times when Dependabot creates then labels a PR
          !((github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' && github.event.action == 'opened') ||
            (github.actor != 'dependabot[bot]' && github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'process-existing-pr'))
        id: skip
        run: echo "Run not needed for this PR, skipping remaining steps"

      - name: Checkout code
        if: steps.skip.outcome == 'skipped'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Fetch all history so that we can get the release branch names
          path: current_repo

      - name: Get release branch names
        if: steps.skip.outcome == 'skipped'
        id: get_release_branch_names
        run: |
          all_branches=$(git branch -r --format='%(refname:short)')
          release_branches=$(echo "$all_branches" | grep -E 'release/.*0$' | tr '\n' ',' | sed 's/,$//')
          echo "release_branches=$release_branches" >> $GITHUB_OUTPUT
        working-directory: current_repo

      - name: Log release branch names
        if: steps.skip.outcome == 'skipped'
        run: echo "Release branch names ${{ steps.get_release_branch_names.outputs.release_branches }}"

      - name: Checkout code from macuject/.github repo
        uses: actions/checkout@v3
        with:
          repository: macuject/.github
          path: reusable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch dotenv @actions/core @actions/github
        working-directory: reusable

      - id: get-members
        uses: garnertb/get-team-members@v1
        with:
          org: macuject
          team_slug: ${{ inputs.github_team }}
          token: ${{ secrets.ORG_TEAM_MEMBERS }}

      - run: "echo ${{ steps.get-members.outputs.members }}"
        shell: bash

      - name: Assign GH team member as reviewer # Assign a random member of the specified GitHub Org team as reviewer
        if: steps.skip.outcome == 'skipped'
        run: node reusable/.github/workflows/assign-reviewer.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TEAM: ${{ inputs.github_team }}
          AMOUNT: 1
          ALL_MEMBERS: ${{ steps.get-members.outputs.members }}
          EXCLUDE_MEMBERS: ${{ inputs.dependabot_exclude_team_members }}

      - name: Get PR reviewer # To be used to assign Jira issue to the same person
        if: steps.skip.outcome == 'skipped'
        id: get_reviewer
        run: | # Use the first reviewer request (PR not yet reviewed), or if none, the first review (PR already reviewed)
          reviewer_username=$(gh pr view ${{ github.event.pull_request.number }} --json reviewRequests --jq '.reviewRequests[0].login')
          if [[ -z "$reviewer_username" ]]; then
            reviewer_username=$(gh pr view ${{ github.event.pull_request.number }} --json reviews --jq '.reviews[0].author.login')
          fi
          echo "reviewer=$reviewer_username" >> $GITHUB_OUTPUT
        working-directory: current_repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Jira
        if: steps.skip.outcome == 'skipped'
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create Jira issue
        if: steps.skip.outcome == 'skipped'
        id: create
        uses: macuject/gajira-create@v1.0.0
        with:
          project: ${{ inputs.project }}
          issuetype: ${{ inputs.issue_type }}
          isSec: true
          summary: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          prlink: ${{ github.event.pull_request._links.html.href }}
          labels: ${{ inputs.labels }}
          assignee: ${{ steps.get_reviewer.outputs.reviewer }}
          releaseBranches: ${{ steps.get_release_branch_names.outputs.release_branches }}
          githubJiraUserMap: ${{ vars.GH_JIRA_USER_MAP }}

      - name: Transition Jira issue to In Review
        if: steps.skip.outcome == 'skipped'
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.create.outputs.issue }}
          transition: In Review

      - name: Log created issue
        if: steps.skip.outcome == 'skipped'
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"

      - name: Rename pull request to include Jira issue number
        if: steps.skip.outcome == 'skipped'
        run: |
          gh pr edit ${{ github.event.pull_request.number }} \
            --title "${{ steps.create.outputs.issue }}: ${{ github.event.pull_request.title }}"
        working-directory: current_repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Jira issue link as comment on PR
        if: steps.skip.outcome == 'skipped'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "Associated Jira issue: https://macuject.atlassian.net/browse/${{ steps.create.outputs.issue }}"
        working-directory: current_repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
