name: Jira

on:
  workflow_call:
    inputs:
      project:
        description: The key of the Jira project to create the issue in
        required: true
        type: string
      github_team:
        description: The name of the GitHub Org team to assign the issue to
        required: true
        type: string
      issue_type:
        description: The type of issue to create
        required: false
        default: Task
        type: string
      labels:
        description: Comma-separated list of labels to apply to the issue
        required: false
        default: security, dependabot
        type: string
    secrets:
      JIRA_BASE_URL:
        required: true
      JIRA_USER_EMAIL:
        required: true
      JIRA_API_TOKEN:
        required: true
      READ_ONLY_ORG_TEAM_MEMBERS:
        required: true

jobs:
  Create: # Create a new Jira issue when a PR is opened by dependabot, or when a PR is labeled with 'process-existing-pr'
    runs-on: ubuntu-latest
    steps:
      - name: Skip remaining steps # Run this rather than just skipping the whole job, so that we see a green tick in the PR checks
        if: >- # Specificity is important here to avoid triggering this action multiple times when Dependabot creates then labels a PR
          !((github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' && github.event.action == 'opened') ||
            (github.actor != 'dependabot[bot]' && github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'process-existing-pr'))
        id: skip
        run: echo "Run not needed for this PR, skipping remaining steps"

      - name: Checkout code
        if: steps.skip.outcome == 'skipped'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Fetch all history so that we can get the release branch names

      - name: Get release branch names
        if: steps.skip.outcome == 'skipped'
        id: get_release_branch_names
        run: |
          all_branches=$(git branch -r --format='%(refname:short)')
          release_branches=$(echo "$all_branches" | grep -E 'release/.*0$' | tr '\n' ',' | sed 's/,$//')
          echo "release_branches=$release_branches" >> $GITHUB_OUTPUT

      - name: Log release branch names
        if: steps.skip.outcome == 'skipped'
        run: echo "Release branch names ${{ steps.get_release_branch_names.outputs.release_branches }}"

      - name: Get random github team member from specified team
        if: steps.skip.outcome == 'skipped'
        id: get_random_github_team_member
        run: |
          MEMBERS=$(curl -s -H "Authorization: token ${{ secrets.READ_ONLY_ORG_TEAM_MEMBERS }}" \
          "https://api.github.com/orgs/macuject/teams/${{ inputs.github_team }}/members")
          RANDOM_MEMBER=$(echo "$MEMBERS" | jq -r '.[] | .login' | shuf -n 1)
          echo "random_team_member=$RANDOM_MEMBER" >> $GITHUB_OUTPUT

      - name: Log random github team member
        if: steps.skip.outcome == 'skipped'
        run: echo "Random GitHub team member ${{ steps.get_random_github_team_member.outputs.random_team_member }}"

      - name: Assign random github team member as reviewer
        if: steps.skip.outcome == 'skipped'
        run: |
          gh pr edit ${{ github.event.pull_request.number }} \
            --add-reviewer ${{ steps.get_random_github_team_member.outputs.random_team_member }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Jira
        if: steps.skip.outcome == 'skipped'
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create Jira issue
        if: steps.skip.outcome == 'skipped'
        id: create
        uses: macuject/gajira-create@v1.0.0
        with:
          project: ${{ inputs.project }}
          issuetype: ${{ inputs.issue_type }}
          isSec: true
          summary: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          prlink: ${{ github.event.pull_request._links.html.href }}
          labels: ${{ inputs.labels }}
          assignee: ${{ steps.get_random_github_team_member.outputs.random_team_member }}
          releaseBranches: ${{ steps.get_release_branch_names.outputs.release_branches }}
          githubJiraUserMap: ${{ vars.GH_JIRA_USER_MAP }}

      - name: Transition Jira issue to In Review
        if: steps.skip.outcome == 'skipped'
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.create.outputs.issue }}
          transition: In Review

      - name: Log created issue
        if: steps.skip.outcome == 'skipped'
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"

      - name: Rename pull request to include Jira issue number
        if: steps.skip.outcome == 'skipped'
        run: |
          gh pr edit ${{ github.event.pull_request.number }} \
            --title "${{ steps.create.outputs.issue }}: ${{ github.event.pull_request.title }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Jira issue link as comment on PR
        if: steps.skip.outcome == 'skipped'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "Associated Jira issue: https://macuject.atlassian.net/browse/${{ steps.create.outputs.issue }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
